version: '3'

services:
  nginx:
    image: nginx:shivi
    container_name: nginx
    restart: unless-stopped
      #network_mode: "host"
    ports:
      #- 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /var/lib/tailscale/certs:/etc/ssl/private
    networks:
      - front_some-net
networks:
  front_some-net:
    driver: bridge
    #    external: true
